apiVersion: skaffold/v4beta9
kind: Config
build:
  artifacts:
    - image: hubimage

profiles:
  - name: reference
    deploy:
      helm:
        releases:
          - name: jupyterhub
            remoteChart: eoepca/application-hub
            namespace: jupyter
            version: 4.0.1
            createNamespace: true
            valuesFiles: []
            setValueTemplates:
              jupyterhub.hub.image.name: "{{.IMAGE_REPO_hubimage}}"
              jupyterhub.hub.image.tag: "{{.IMAGE_TAG_hubimage}}@{{.IMAGE_DIGEST_hubimage}}"
            setValues:
              jupyterhub.hub.image.pullSecrets: ["eoepca-plus-secret-ro"]
              jupyterhub.hub.db.pvc.storageClassName: scw-bssd
              jupyterhub.hub.extraEnv.STORAGE_CLASS: scw-bssd
              jupyterhub.proxy.secretToken: "032d5bfe141a7eab86d57587879b33c5d168617cacb339823d7f47fe2933f880"
              jupyterhub.hub.extraEnv.APP_HUB_NAMESPACE: jupyter
              jupyterhub.hub.networkPolicy.enabled: false
            setFiles:
              configYml: ./files/hub/config.yml
              jupyterConfig: ./files/hub/jupyterhub_config.py

    manifests:
      rawYaml:
      - sk-k8s/cluster-role-binding.yaml
      - sk-k8s/script.yaml
      - sk-k8s/job.yaml

  - name: minikube
    deploy:
      helm:
        releases:
          - name: jupyterhub
            remoteChart: eoepca/application-hub
            namespace: jupyter
            version: 4.0.1
            createNamespace: true
            valuesFiles: []
            setValueTemplates:
              jupyterhub.hub.image.name: "{{.IMAGE_REPO_hubimage}}"
              jupyterhub.hub.image.tag: "{{.IMAGE_TAG_hubimage}}@{{.IMAGE_DIGEST_hubimage}}"
            setValues:
              jupyterhub.hub.image.pullSecrets: []
              jupyterhub.hub.db.pvc.storageClassName: standard
              jupyterhub.hub.extraEnv.STORAGE_CLASS: standard
              jupyterhub.proxy.secretToken: "032d5bfe141a7eab86d57587879b33c5d168617cacb339823d7f47fe2933f880"
              jupyterhub.hub.extraEnv.APP_HUB_NAMESPACE: jupyter
              jupyterhub.hub.networkPolicy.enabled: false
            setFiles:
              configYml: ./files/hub/config.yml
              jupyterConfig: ./files/hub/jupyterhub_config.py

    manifests:
      rawYaml:
      - sk-k8s/cluster-role-binding.yaml
      - sk-k8s/script.yaml
      - sk-k8s/job.yaml

  # - name: eoepca-demo
  #   deploy:
  #     helm:
  #       releases:
  #         - name: jupyterhub
  #           chartPath: jupyterhub
  #           namespace: jupyter
  #           createNamespace: true
  #           valuesFiles:
  #             - demo-eoepca-values.yaml
  #           setValueTemplates:
  #             hub.image.name: "{{.IMAGE_REPO_hubimage}}"
  #             hub.image.tag: "{{.IMAGE_TAG_hubimage}}"
  #             hub.image.pullPolicy: "Always"
  #             hub.db.pvc.storageClassName: "managed-nfs-storage"
  #             hub.image.pullSecrets: 
  #             - "eoepca-plus-secret-ro"
  #           setFiles: {
  #             appHubConfig: ./eoepca-demo/config.yml,
  #             pageTheme: ./files/theme/page.html,
  #             spawnPendingTheme: ./files/theme/spawn_pending.html,
  #             spawnTheme: ./files/theme/spawn.html
  #           }

  #   manifests:
  #     rawYaml:
  #     - sk-k8s/cluster-role-binding.yaml
  #     - sk-k8s/script.yaml
  #     - sk-k8s/job.yaml
portForward:
- resourceType: service
  resourceName: application-hub-proxy-public
  namespace: jupyter # Optional, if you are using a specific namespace
  port: 80 # Target port on the pod
  localPort: 8000 # Local port on your machine
