apiVersion: skaffold/v4beta9
kind: Config
build:
  artifacts:
    - image: hubimage

profiles:
  - name: reference
    deploy:
      helm:
        releases:
          - name: jupyterhub
            chartPath: jupyterhub
            namespace: jupyter
            createNamespace: true
            valuesFiles:
              - demo-values.yaml
            setValueTemplates:
              hub.image.name: "{{.IMAGE_REPO_hubimage}}/{{.IMAGE_TAG_hubimage}}@{{.IMAGE_DIGEST_hubimage}}"
            setFiles: {
              appHubConfig: ./files/hub/config.yml,
              pageTheme: ./files/theme/page.html,
              spawnPendingTheme: ./files/theme/spawn_pending.html,
              spawnTheme: ./files/theme/spawn.html
            }

    manifests:
      rawYaml:
      - sk-k8s/cluster-role-binding.yaml
      - sk-k8s/script.yaml
      - sk-k8s/job.yaml

portForward:
- resourceType: service
  resourceName: proxy-public
  namespace: jupyter # Optional, if you are using a specific namespace
  port: 80 # Target port on the pod
  localPort: 8000 # Local port on your machine
