kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "jupyterhub.hub.fullname" . }}-theme
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
data:
  {{- /*
    Glob files to allow them to be mounted by the hub pod

    jupyterhub_config: |
      multi line string content...
    z2jh.py: |
      multi line string content...
  */}}
    # templates for the hub
  page.html: {{ required "A valid .Values.pageTheme entry required!" (tpl (.Values.pageTheme | default (.Files.Get "files/theme/page.html")) . | quote ) }}
  spawn_pending.html: {{ required "A valid .Values.spawnPendingTheme entry required!" (tpl (.Values.spawnPendingTheme | default (.Files.Get "files/theme/spawn_pending.html")) . | quote ) }}
  spawn.html: {{ required "A valid .Values.spawnTheme entry required!" (tpl (.Values.spawnTheme | default (.Files.Get "files/theme/spawn.html")) . | quote) }}

  {{- /*
    Store away a checksum of the hook-image-puller daemonset so future upgrades
    can compare and decide if it should run or not using the `lookup` function.
  */}}
  checksum_hook-image-puller: {{ include "jupyterhub.imagePuller.daemonset.hook.checksum" . | quote }}
