kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "jupyterhub.hub.fullname" . }}
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
data:
  {{- /*
    Resource names exposed to reliably reference them.

    user-scheduler: "my-helm-release-user-scheduler"
    ...
  */}}
  {{- include "jupyterhub.name-templates" . | nindent 2 }}

  {{- /*
    Glob files to allow them to be mounted by the hub pod

    jupyterhub_config: |
      multi line string content...
    z2jh.py: |
      multi line string content...
  */}}
  config.yml: {{ required "A valid .Values.appHubConfig entry required!" (tpl (.Values.appHubConfig | default (.Files.Get "files/hub/config.yml")) . | quote) }}
  jupyterhub_config.py: {{ required "A valid .Values.jupHubConfig entry required!" (tpl (.Values.jupHubConfig | default (.Files.Get "files/hub/jupyterhub_config.py")) . | quote) }}
  z2jh.py: {{ required "A valid .Values.z2jhConfig entry required!" (tpl (.Values.z2jhConfig | default (.Files.Get "files/hub/z2jh.py")) . | quote) }}



  {{- /*
    Store away a checksum of the hook-image-puller daemonset so future upgrades
    can compare and decide if it should run or not using the `lookup` function.
  */}}
  checksum_hook-image-puller: {{ include "jupyterhub.imagePuller.daemonset.hook.checksum" . | quote }}
